#!/bin/bash
#
# cd into the package service path i.e. /hab/svc/rabbitmq
cd {{pkg.svc_path}}

# RMQ is different in that the rabbitmq-server command runs an exec
# to start the process and it looks like habitat loses the pid
# so lets send the "stop" command before we start
kill -TERM `pgrep beam`

exec 2>&1
exec /usr/bin/env \
  HOSTNAME=localhost \
  RABBITMQ_CONF_ENV_FILE={{pkg.svc_config_path}}/rabbitmq-env.conf \
  HOME={{pkg.svc_path}}/var/lib/rabbitmq \
  chpst -u hab:hab {{pkg.svc_path}}/sbin/rabbitmq-server
