#!/bin/bash
#
cd {{pkg.svc_path}}

ulimit -a

exec 2>&1
exec /usr/bin/env \
  HOSTNAME=localhost \
  RABBITMQ_CONF_ENV_FILE={{pkg.svc_config_path}}/rabbitmq-env.conf \
  HOME={{pkg.svc_path}}/var/lib/rabbitmq \
  chpst -u hab:hab {{pkg.svc_path}}/sbin/rabbitmq-server
